Create Shell script which runs clang-format on all staged files
lethal-guitar/RigelEngine pull request #824
Opened 2022-01-22 21:41 UTC by mohitsaxenaknoldus

Closes #815

2022-01-22 22:33 UTC, lethal-guitar commented
Awesome, thanks! I'll check it out tomorrow.

2022-01-23 09:41 UTC, lethal-guitar requested changes
Thanks a lot for taking this on, really appreciate it! I've tested it and it generally works well, aside from not covering all file extensions (see comment). However, there are two cases that don't work currently:

1. When running the script from a path that's different from the repository root, the clang-format invocation fails with a "file not found error" due to the list of staged files being relative to the repository root. For example, running the script from the `build` directory: `../tools/format-staged.sh`. That's a very common use case, so it would be nice to make it possible.
2. Running the script via the Ubuntu Docker container doesn't work because there is no `git` installed in the container.

2022-01-23 09:41 UTC, lethal-guitar commented on tools/format-staged.sh
> +  if [[ "$file" =~ \.cpp$ ]]; then
`.hpp` and `.ipp` are additional extensions that need to be included when formatting.

2022-01-23 09:41 UTC, lethal-guitar commented on tools/format-staged.sh
> +    $CLANG_FORMAT -i $file
Just to be on the safe side, I'd recommend quoting `$file` here, i.e. `"$file"`. In case there are files with spaces in the name or similar.

2022-01-23 22:37 UTC, lethal-guitar reviewed
Thanks for the update, that should do it for the file extensions. Did you see my other comments regarding usage with Docker and from a different directory?

2022-01-24 08:05 UTC, mohitsaxenaknoldus commented
> Thanks for the update, that should do it for the file extensions. Did you see my other comments regarding usage with Docker and from a different directory?

Now you should be able to run it from any directory and I've added git to the Dockerfile because without it, it won't be possible to get the list of the changed files.

2022-01-24 09:02 UTC, lethal-guitar commented
Great, thanks! 👍🏻🎉 I'll be busy for the next couple days, but I should be able to get back to you sometime next weekend. Very happy to have this!

2022-01-29 14:26 UTC, lethal-guitar approved these changes

2022-01-29 15:56 UTC, merged

2022-01-29 16:02 UTC, lethal-guitar commented
Thanks again for your contribution. I had to make some more changes:

* Installing `git` in the Dockerfile didn't work because of a missing `-y` argument and usage of `sudo` (which isn't available in the Ubuntu base image)
* Only the first staged file was formatted, because the result of `git diff` wasn't escaped

I also simplified the file extension filtering.